spring:
  application:
    name: core-apigateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081  # Auth Service? ???? URI
          predicates:
            - Path=/api/v1/auth/**, /api/v1/health/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**
        - id: core-product-api
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/products/**
        - id: core-order-api
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/orders/**